name: lissero
description: Serotype prediction tool for Listeria monocytogenes
keywords:
  - serotype
tools:
  - lissero:
      description: |
        Serotype prediction tool for Listeria monocytogenes
      documentation: https://github.com/MDU-PHL/lissero
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: |
        List of input Fasta files.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - typer:
      type: file
      description: typer output
      pattern: "typer.txt"

authors:
  - "@kristyhoran"
  
