name: ska2
description: 
keywords:
  - ska2
tools:
  - ska2:
      description: |
        Split k-mer analysis (version 2) uses exact matching of split k-mer sequences to align closely related sequences, typically small haploid genomes such as bacteria and viruses.
      documentation: https://github.com/bacpop/ska.rust
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  
  - aln:
      type: file
      description: |
        ska sketch

output:
  
  - distances:
      type: file
      description: distances output file
      pattern: "distances.tsv"
authors:
  - "@kristyhoran"
  
