name: mob_suite
description: |
  Software tools for clustering, reconstruction and typing of plasmids from draft assemblies
keywords:
  - plasmid
tools:
  - mob_suite:
      description: |
        Software tools for clustering, reconstruction and typing of plasmids from draft assemblies
      documentation: https://github.com/phac-nml/mob-suite
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: |
        List of input contig files for analysis.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contig_report:
      type: file
      description: The contig_report file from mobsuite
      pattern: "contig_report.txt"
  - mobs:
      type: file
      description: The mobs results file from mobsuite
      pattern: "mobtype_results.txt"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
