name: quicktree
description: 
keywords:
  - phylogenetics
tools:
  - quicktree:
      description: |
        QuickTree is a tool for building trees from distances.
      documentation: https://github.com/khowe/quicktree
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  
  - distances:
      type: file
      description: |
        Distance matrix for phylogenetic analysis.

output:
  - newick:
      type: file
      description: The Newick format tree file
      pattern: "*.newick"
authors:
  - "@kristyhoran"
  
