name: abritamr
description: A pipeline for running AMRfinderPlus and collating results into functional classes
keywords:
  - amr
tools:
  - shovill:
      description: |
          A pipeline for running AMRfinderPlus and collating results into functional classes
      documentation: https://github.com/mdu-phl/abritamr
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: |
        List of input contig files  .

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: The report file from kraken2
      pattern: "*.contigs.fa"
  - log:
      type: file
      description: fastq log file
      pattern: "*.shovill.log"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
