name: gubbins
description: Remove potenetially recombined regions from a multiple sequence alignment
keywords:
  - recombination
tools:
  - gubbins:
      description: |
        Remove potentially recombined regions from a multiple sequence alignment
      documentation: https://github.com/sanger-pathogens/gubbins
      doi: https://doi.org/10.1093/nar/gku1196
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
 
input:

  - cleaned_alignment:
      type: file
      description: |
        A cleaned multiple sequence alignment file, typically in FASTA format,
        that has been processed to remove low-quality sequences and regions.

output:
  - gubbins_output:
      type: file
      description: alignment output from gubbins
      pattern: "gubbins.aln"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
