name: panaroo
description: 
  Panaroo is a pangenome pipeline for prokaryotes that can be used to infer gene presence/absence, core and accessory genomes, and gene trees.
keywords:
  - pangenome
tools:
  - panaroo:
      description: |
        Panaroo is a pangenome pipeline for prokaryotes that can be used to infer gene presence/absence, core and accessory genomes, and gene trees.
      documentation: https://github.com/gtonkinhill/panaroo
      doi: https://doi.org/10.1186/s13059-019-1891-0
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  
input:
  - gff:
      type: file
      description: |
        GFF file containing gene annotations for the input genomes.
  
output:
  - pangenome_summary:
      type: file
      description: The pangenome output file containing gene presence/absence information.
      pattern: "pangenome_statistics.tsv"
  - pangenome_csv:
      type: file
      description: The pangenome output file containing gene presence/absence information in roary format.
      pattern: "gene_presence_absence_roary.csv"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
