name: prokka
description: Annotate bacterial isolate genomes from Illumina paired-end reads.
  Prokka is a software tool that provides rapid annotation of prokaryotic genomes.
keywords:
  - assembly
tools:
  - prokka:
      description: |
        Annotate bacterial isolate genomes from Illumina paired-end reads.
        Prokka is a software tool that provides rapid annotation of prokaryotic genomes.
      documentation: https://github.com/tseemann/prokka
      doi:
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: |
        List of input contig files to be annotated.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - gff:
      type: file
      description: The graph file from prokka
      pattern: "*.gff"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
