name: seqkit
description: 
keywords:
  - quality control
tools:
  - seqkit:
      description: |
        SeqKit is a tool for fast and efficient sequence manipulation.
      documentation: https://github.com/shenwei356/seqkit
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input_files:
      type: file
      description: |
        fastq or fasta files to be processed by seqkit.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - stats:
      type: file
      description: The statistics file from seqkit
      pattern: "read_qual.txt"
authors:
  - "@kristyhoran"
  
