name: veryfasttree
description: |
  A tool for constructing phylogenetic trees from genomic data
keywords:
  - assembly
tools:
  - veryfasttree:
      description: |
        VeryFastTree is a tool for constructing phylogenetic trees from genomic data.
      documentation: https://github.com/bluenote-1577/sylph
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - aln:
      type: file
      description: |
        cleaned alignment file.
  

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - newick:
      type: file
      description: The newick file from IQ-TREE
      pattern: "*.newick"
authors:
  - "@kristyhoran"
  
