name: snpdists
description: Calculate SNP distances between sequences
keywords:
  - distances
tools:
  - snp-dists:
      description: |
        SNP-Dists is a tool for calculating SNP distances between sequences.
      documentation: https://github.com/tseemann/snp-dists
      doi: 
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  
  - aln:
      type: file
      description: |
        aligned sequences in FASTA format for SNP distance calculation.
output:
  - distances:
      type: file
      description: The SNP distance matrix file
      pattern: "*.tsv"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@kristyhoran"
  
