name: kleborate
description: kleborate is a tool for the rapid identification of Klebsiella pneumoniae
  sequence types and virulence factors from whole genome sequencing data.
keywords:
  - serotype
tools:
  - kleborate:
      description: |
        kleborate is a tool for the rapid identification of Klebsiella pneumoniae
        sequence types and virulence factors from whole genome sequencing data.
      documentation: https://github.com/katholt/kleborate
      doi:
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - contigs:
      type: file
      description: |
        List of input contig files for the alignment process.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - typer:
      type: file
      description: typer output
      pattern: "typer.txt"

authors:
  - "@kristyhoran"
  
